/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package DaysOfKotlinAndVertx

import io.vertx.core.AbstractVerticle
import io.vertx.core.Vertx
import io.vertx.ext.web.Router

class App:AbstractVerticle(){

    override fun start() {
        var router = Router.router(vertx)
        router.get("/").handler({rc -> rc.response().end("hello")})
        router.get("/:name").handler({rc -> rc.response().end("hello ${rc.pathParam("name")}")})
        vertx.createHttpServer().requestHandler(router).listen(8000)
    }


}

fun main(args: Array<String>) {
    Vertx.vertx().deployVerticle(App())
}
