/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package DaysOfKotlinAndVertx

import io.vertx.core.AbstractVerticle
import io.vertx.core.Vertx

class App:AbstractVerticle(){

    // Called when verticle is deployed
    override fun start() {
        print("hello")
        var server = vertx.createHttpServer()
        server.requestHandler({ req ->
            req.response().end("Hello World!")
        })
        server.listen()
    }
    // Optional - called when verticle is undeployed
    override fun stop() {
        print("good bye")
    }
}

fun main(args: Array<String>) {
//    Using the below commented code HTTP Server is not associated with any verticle
//    var server = Vertx.vertx().createHttpServer()
//    server.requestHandler({req ->
//        req.response().end("Hello World!")
//    })
//    server.listen()
    Vertx.vertx().deployVerticle(App())
}
